// Generated by jextract

package com.github.cubiomes;

/**
 * {@snippet lang=c :
 * typedef struct _iobuf {
 *     void *_Placeholder;
 * } FILE
 * }
 */
public class FILE extends _iobuf {

    FILE() {
        // Should not be called directly
    }
}

