// Generated by jextract

package com.github.cubiomes;

/**
 * {@snippet lang=c :
 * typedef _Lldiv_t imaxdiv_t
 * }
 */
public class imaxdiv_t extends _Lldiv_t {

    imaxdiv_t() {
        // Should not be called directly
    }
}

