// Generated by jextract

package com.github.cubiomes;

/**
 * {@snippet lang=c :
 * typedef struct _ldiv_t {
 *     long quot;
 *     long rem;
 * } ldiv_t
 * }
 */
public class ldiv_t extends _ldiv_t {

    ldiv_t() {
        // Should not be called directly
    }
}

