// Generated by jextract

package com.github.cubiomes;

/**
 * {@snippet lang=c :
 * typedef _Mbstatet mbstate_t
 * }
 */
public class mbstate_t extends _Mbstatet {

    mbstate_t() {
        // Should not be called directly
    }
}

